Set up Angular Project
googleinterns/step273-2020 pull request #17
Opened 2021-01-13 04:38 UTC by helenatran

Integrate maven and angular to set up the project. 

To run the application:
- npm run build
- npm run dev

2021-01-13 04:42 UTC, jamila-sabaz approved these changes

2021-01-13 04:57 UTC, g-wittie requested changes
Looks good, but clean up the things you're not using.

2021-01-13 04:57 UTC, g-wittie commented on package-lock.json
> +{
Don't commit this file, npm will (re)generate it for you.

2021-01-13 04:57 UTC, g-wittie commented on package.json
> +  "dependencies": {
You're probably not using most of these dependencies, get rid of the ones you don't need.

2021-01-13 04:57 UTC, g-wittie commented on src/main/webapp/e2e/protractor.conf.js
> +// @ts-check
Remove the e2e directory since you don't have any end-to-end tests yet.

2021-01-13 04:57 UTC, g-wittie commented on src/main/webapp/package-lock.json
> +{
Again, don't check this in and .gitignore it.

2021-01-13 04:57 UTC, g-wittie commented on src/main/webapp/package.json
> +{
Pare this down to what you need, e.g. you don't have end to end tests yet so no need for "e2e", and you're not using most of those dependencies so remove them.

2021-01-13 23:22 UTC, g-wittie commented on src/main/webapp/angular.json
> +{
This file also contains some extraneous config, e.g. e2e.

2021-01-13 23:34 UTC, helenatran commented
Thanks @g-wittie for the feedback. I have made some changes, but I was not sure at 100% which dependencies I should remove. Let me know whether I have missed some. Also, I tried to put the package-lock.json in the .gitignore file, but it doesn't seem to ignore them?

2021-01-14 00:35 UTC, g-wittie commented
> Thanks @g-wittie for the feedback. I have made some changes, but I was not sure at 100% which dependencies I should remove. Let me know whether I have missed some. Also, I tried to put the package-lock.json in the .gitignore file, but it doesn't seem to ignore them. How can I make sure they don't get committed?

Re. the dependencies, it's probably mostly a matter of trial and error. Take out everything you're not sure about and rebuild the app, if it still works fine then those dependencies should be ok to remove. I'm fine if you add a cleanup bug to do this later so you can get this PR merged to unblock the team.

Re. package-lock.json, since you've already added package-lock.json to the index just adding it to .gitignore won't work. You need to remove the file from the index with `git rm`, then .gitignore should work.

2021-01-14 00:39 UTC, g-wittie approved these changes

2021-01-14 00:41 UTC, merged