Add the option to filter the ranking
googleinterns/step273-2020 pull request #78
Opened 2021-02-12 11:03 UTC by helenatran

This PR creates buttons which allow the user to filter the ranking to:
- view a ranking of both restaurants and cafes
- view a ranking of only restaurants
- view a ranking of only cafes

<img width="1440" alt="Screen Shot 2021-02-12 at 7 27 03 pm" src="https://user-images.githubusercontent.com/53108940/107760545-090bb080-6d7e-11eb-9b32-004ddcd6fef0.png">

2021-02-14 23:01 UTC, lorikeet-s requested changes

2021-02-14 23:01 UTC, lorikeet-s commented on src/main/webapp/src/app/ranking/ranking-list/ranking-list.component.ts
>        this.hiddenGems = this.appComponent.hiddenGems;
There's a lot more arrays now than there were before, it's obvious what's happening when you look at the html file but could you add a comment here or at the top of the class explaining briefly what the arrays are used for so flipping over the html file is not necessary

2021-02-15 04:28 UTC, lorikeet-s approved these changes

2021-02-15 05:46 UTC, sehhajdkg approved these changes

2021-02-15 05:46 UTC, sehhajdkg commented on src/main/webapp/src/app/ranking/ranking-list/ranking-list.component.ts
>  import { Location } from 'src/app/models/location';
nit - we can remove location and location service now that we have the app component hidden gems

2021-02-15 05:46 UTC, sehhajdkg commented on src/main/webapp/src/app/ranking/ranking-list/ranking-list.component.ts
>    location = {} as Location;
delete hehe

2021-02-15 05:46 UTC, sehhajdkg commented on src/main/webapp/src/app/ranking/ranking-list/ranking-list.component.ts
>    constructor(private locationService: LocationService, private appComponent: AppComponent) { }
remove location service from here :)

2021-02-15 22:34 UTC, merged